final List<Map<String, dynamic>> countryCodes = [
  {
    "phone_code": "93",
    "country_code": "AF",
    "name": "Afghanistan",
    "display_name": "Afghanistan (AF) [+93]",
  },
  {
    "phone_code": "358",
    "country_code": "AX",
    "name": "Åland Islands",
    "display_name": "Åland Islands (AX) [+358]",
  },
  {
    "phone_code": "355",
    "country_code": "AL",
    "name": "Albania",
    "display_name": "Albania (AL) [+355]",
  },
  {
    "phone_code": "213",
    "country_code": "DZ",
    "name": "Algeria",
    "display_name": "Algeria (DZ) [+213]",
  },
  {
    "phone_code": "1",
    "country_code": "AS",
    "name": "American Samoa",
    "display_name": "American Samoa (AS) [+1]",
  },
  {
    "phone_code": "376",
    "country_code": "AD",
    "name": "Andorra",
    "display_name": "Andorra (AD) [+376]",
  },
  {
    "phone_code": "244",
    "country_code": "AO",
    "name": "Angola",
    "display_name": "Angola (AO) [+244]",
  },
  {
    "phone_code": "1",
    "country_code": "AI",
    "name": "Anguilla",
    "display_name": "Anguilla (AI) [+1]",
  },
  {
    "phone_code": "1",
    "country_code": "AG",
    "name": "Antigua and Barbuda",
    "display_name": "Antigua and Barbuda (AG) [+1]",
  },
  {
    "phone_code": "54",
    "country_code": "AR",
    "name": "Argentina",
    "display_name": "Argentina (AR) [+54]",
  },
  {
    "phone_code": "374",
    "country_code": "AM",
    "name": "Armenia",
    "display_name": "Armenia (AM) [+374]",
  },
  {
    "phone_code": "297",
    "country_code": "AW",
    "name": "Aruba",
    "display_name": "Aruba (AW) [+297]",
  },
  {
    "phone_code": "247",
    "country_code": "AC",
    "name": "Ascension Island",
    "display_name": "Ascension Island (AC) [+247]",
  },
  {
    "phone_code": "61",
    "country_code": "AU",
    "name": "Australia",
    "display_name": "Australia (AU) [+61]",
  },
  {
    "phone_code": "43",
    "country_code": "AT",
    "name": "Austria",
    "display_name": "Austria (AT) [+43]",
  },
  {
    "phone_code": "994",
    "country_code": "AZ",
    "name": "Azerbaijan",
    "display_name": "Azerbaijan (AZ) [+994]",
  },
  {
    "phone_code": "1",
    "country_code": "BS",
    "name": "Bahamas",
    "display_name": "Bahamas (BS) [+1]",
  },
  {
    "phone_code": "973",
    "country_code": "BH",
    "name": "Bahrain",
    "display_name": "Bahrain (BH) [+973]",
  },
  {
    "phone_code": "880",
    "country_code": "BD",
    "name": "Bangladesh",
    "display_name": "Bangladesh (BD) [+880]",
  },
  {
    "phone_code": "1",
    "country_code": "BB",
    "name": "Barbados",
    "display_name": "Barbados (BB) [+1]",
  },
  {
    "phone_code": "375",
    "country_code": "BY",
    "name": "Belarus",
    "display_name": "Belarus (BY) [+375]",
  },
  {
    "phone_code": "32",
    "country_code": "BE",
    "name": "Belgium",
    "display_name": "Belgium (BE) [+32]",
  },
  {
    "phone_code": "501",
    "country_code": "BZ",
    "name": "Belize",
    "display_name": "Belize (BZ) [+501]",
  },
  {
    "phone_code": "229",
    "country_code": "BJ",
    "name": "Benin",
    "display_name": "Benin (BJ) [+229]",
  },
  {
    "phone_code": "1",
    "country_code": "BM",
    "name": "Bermuda",
    "display_name": "Bermuda (BM) [+1]",
  },
  {
    "phone_code": "975",
    "country_code": "BT",
    "name": "Bhutan",
    "display_name": "Bhutan (BT) [+975]",
  },
  {
    "phone_code": "591",
    "country_code": "BO",
    "name": "Bolivia",
    "display_name": "Bolivia (BO) [+591]",
  },
  {
    "phone_code": "387",
    "country_code": "BA",
    "name": "Bosnia and Herzegovina",
    "display_name": "Bosnia and Herzegovina (BA) [+387]",
  },
  {
    "phone_code": "267",
    "country_code": "BW",
    "name": "Botswana",
    "display_name": "Botswana (BW) [+267]",
  },
  {
    "phone_code": "55",
    "country_code": "BR",
    "name": "Brazil",
    "display_name": "Brazil (BR) [+55]",
  },
  {
    "phone_code": "246",
    "country_code": "IO",
    "name": "British Indian Ocean Territory",
    "display_name": "British Indian Ocean Territory (IO) [+246]",
  },
  {
    "phone_code": "1",
    "country_code": "VG",
    "name": "British Virgin Islands",
    "display_name": "British Virgin Islands (VG) [+1]",
  },
  {
    "phone_code": "673",
    "country_code": "BN",
    "name": "Brunei",
    "display_name": "Brunei (BN) [+673]",
  },
  {
    "phone_code": "359",
    "country_code": "BG",
    "name": "Bulgaria",
    "display_name": "Bulgaria (BG) [+359]",
  },
  {
    "phone_code": "226",
    "country_code": "BF",
    "name": "Burkina Faso",
    "display_name": "Burkina Faso (BF) [+226]",
  },
  {
    "phone_code": "257",
    "country_code": "BI",
    "name": "Burundi",
    "display_name": "Burundi (BI) [+257]",
  },
  {
    "phone_code": "855",
    "country_code": "KH",
    "name": "Cambodia",
    "display_name": "Cambodia (KH) [+855]",
  },
  {
    "phone_code": "237",
    "country_code": "CM",
    "name": "Cameroon",
    "display_name": "Cameroon (CM) [+237]",
  },
  {
    "phone_code": "1",
    "country_code": "CA",
    "name": "Canada",
    "display_name": "Canada (CA) [+1]",
  },
  {
    "phone_code": "238",
    "country_code": "CV",
    "name": "Cape Verde",
    "display_name": "Cape Verde (CV) [+238]",
  },
  {
    "phone_code": "599",
    "country_code": "BQ",
    "name": "Caribbean Netherlands",
    "display_name": "Caribbean Netherlands (BQ) [+599]",
  },
  {
    "phone_code": "1",
    "country_code": "KY",
    "name": "Cayman Islands",
    "display_name": "Cayman Islands (KY) [+1]",
  },
  {
    "phone_code": "236",
    "country_code": "CF",
    "name": "Central African Republic",
    "display_name": "Central African Republic (CF) [+236]",
  },
  {
    "phone_code": "235",
    "country_code": "TD",
    "name": "Chad",
    "display_name": "Chad (TD) [+235]",
  },
  {
    "phone_code": "56",
    "country_code": "CL",
    "name": "Chile",
    "display_name": "Chile (CL) [+56]",
  },
  {
    "phone_code": "86",
    "country_code": "CN",
    "name": "China",
    "display_name": "China (CN) [+86]",
  },
  {
    "phone_code": "61",
    "country_code": "CX",
    "name": "Christmas Island",
    "display_name": "Christmas Island (CX) [+61]",
  },
  {
    "phone_code": "61",
    "country_code": "CC",
    "name": "Cocos [Keeling] Islands",
    "display_name": "Cocos [Keeling] Islands (CC) [+61]",
  },
  {
    "phone_code": "57",
    "country_code": "CO",
    "name": "Colombia",
    "display_name": "Colombia (CO) [+57]",
  },
  {
    "phone_code": "269",
    "country_code": "KM",
    "name": "Comoros",
    "display_name": "Comoros (KM) [+269]",
  },
  {
    "phone_code": "243",
    "country_code": "CD",
    "name": "Democratic Republic Congo",
    "display_name": "Democratic Republic Congo (CD) [+243]",
  },
  {
    "phone_code": "242",
    "country_code": "CG",
    "name": "Republic of Congo",
    "display_name": "Republic of Congo (CG) [+242]",
  },
  {
    "phone_code": "682",
    "country_code": "CK",
    "name": "Cook Islands",
    "display_name": "Cook Islands (CK) [+682]",
  },
  {
    "phone_code": "506",
    "country_code": "CR",
    "name": "Costa Rica",
    "display_name": "Costa Rica (CR) [+506]",
  },
  {
    "phone_code": "225",
    "country_code": "CI",
    "name": "Côte d'Ivoire",
    "display_name": "Côte d'Ivoire (CI) [+225]",
  },
  {
    "phone_code": "385",
    "country_code": "HR",
    "name": "Croatia",
    "display_name": "Croatia (HR) [+385]",
  },
  {
    "phone_code": "53",
    "country_code": "CU",
    "name": "Cuba",
    "display_name": "Cuba (CU) [+53]",
  },
  {
    "phone_code": "599",
    "country_code": "CW",
    "name": "Curaçao",
    "display_name": "Curaçao (CW) [+599]",
  },
  {
    "phone_code": "357",
    "country_code": "CY",
    "name": "Cyprus",
    "display_name": "Cyprus (CY) [+357]",
  },
  {
    "phone_code": "420",
    "country_code": "CZ",
    "name": "Czech Republic",
    "display_name": "Czech Republic (CZ) [+420]",
  },
  {
    "phone_code": "45",
    "country_code": "DK",
    "name": "Denmark",
    "display_name": "Denmark (DK) [+45]",
  },
  {
    "phone_code": "253",
    "country_code": "DJ",
    "name": "Djibouti",
    "display_name": "Djibouti (DJ) [+253]",
  },
  {
    "phone_code": "1",
    "country_code": "DM",
    "name": "Dominica",
    "display_name": "Dominica (DM) [+1]",
  },
  {
    "phone_code": "1",
    "country_code": "DO",
    "name": "Dominican Republic",
    "display_name": "Dominican Republic (DO) [+1]",
  },
  {
    "phone_code": "670",
    "country_code": "TL",
    "name": "East Timor",
    "display_name": "East Timor (TL) [+670]",
  },
  {
    "phone_code": "593",
    "country_code": "EC",
    "name": "Ecuador",
    "display_name": "Ecuador (EC) [+593]",
  },
  {
    "phone_code": "20",
    "country_code": "EG",
    "name": "Egypt",
    "display_name": "Egypt (EG) [+20]",
  },
  {
    "phone_code": "503",
    "country_code": "SV",
    "name": "El Salvador",
    "display_name": "El Salvador (SV) [+503]",
  },
  {
    "phone_code": "240",
    "country_code": "GQ",
    "name": "Equatorial Guinea",
    "display_name": "Equatorial Guinea (GQ) [+240]",
  },
  {
    "phone_code": "291",
    "country_code": "ER",
    "name": "Eritrea",
    "display_name": "Eritrea (ER) [+291]",
  },
  {
    "phone_code": "372",
    "country_code": "EE",
    "name": "Estonia",
    "display_name": "Estonia (EE) [+372]",
  },
  {
    "phone_code": "268",
    "country_code": "SZ",
    "name": "Eswatini",
    "display_name": "Eswatini (SZ) [+268]",
  },
  {
    "phone_code": "251",
    "country_code": "ET",
    "name": "Ethiopia",
    "display_name": "Ethiopia (ET) [+251]",
  },
  {
    "phone_code": "500",
    "country_code": "FK",
    "name": "Falkland Islands [Islas Malvinas]",
    "display_name": "Falkland Islands [Islas Malvinas] (FK) [+500]",
  },
  {
    "phone_code": "298",
    "country_code": "FO",
    "name": "Faroe Islands",
    "display_name": "Faroe Islands (FO) [+298]",
  },
  {
    "phone_code": "679",
    "country_code": "FJ",
    "name": "Fiji",
    "display_name": "Fiji (FJ) [+679]",
  },
  {
    "phone_code": "358",
    "country_code": "FI",
    "name": "Finland",
    "display_name": "Finland (FI) [+358]",
  },
  {
    "phone_code": "33",
    "country_code": "FR",
    "name": "France",
    "display_name": "France (FR) [+33]",
  },
  {
    "phone_code": "594",
    "country_code": "GF",
    "name": "French Guiana",
    "display_name": "French Guiana (GF) [+594]",
  },
  {
    "phone_code": "689",
    "country_code": "PF",
    "name": "French Polynesia",
    "display_name": "French Polynesia (PF) [+689]",
  },
  {
    "phone_code": "241",
    "country_code": "GA",
    "name": "Gabon",
    "display_name": "Gabon (GA) [+241]",
  },
  {
    "phone_code": "220",
    "country_code": "GM",
    "name": "Gambia",
    "display_name": "Gambia (GM) [+220]",
  },
  {
    "phone_code": "995",
    "country_code": "GE",
    "name": "Georgia",
    "display_name": "Georgia (GE) [+995]",
  },
  {
    "phone_code": "49",
    "country_code": "DE",
    "name": "Germany",
    "display_name": "Germany (DE) [+49]",
  },
  {
    "phone_code": "233",
    "country_code": "GH",
    "name": "Ghana",
    "display_name": "Ghana (GH) [+233]",
  },
  {
    "phone_code": "350",
    "country_code": "GI",
    "name": "Gibraltar",
    "display_name": "Gibraltar (GI) [+350]",
  },
  {
    "phone_code": "30",
    "country_code": "GR",
    "name": "Greece",
    "display_name": "Greece (GR) [+30]",
  },
  {
    "phone_code": "299",
    "country_code": "GL",
    "name": "Greenland",
    "display_name": "Greenland (GL) [+299]",
  },
  {
    "phone_code": "1",
    "country_code": "GD",
    "name": "Grenada",
    "display_name": "Grenada (GD) [+1]",
  },
  {
    "phone_code": "590",
    "country_code": "GP",
    "name": "Guadeloupe",
    "display_name": "Guadeloupe (GP) [+590]",
  },
  {
    "phone_code": "1",
    "country_code": "GU",
    "name": "Guam",
    "display_name": "Guam (GU) [+1]",
  },
  {
    "phone_code": "502",
    "country_code": "GT",
    "name": "Guatemala",
    "display_name": "Guatemala (GT) [+502]",
  },
  {
    "phone_code": "44",
    "country_code": "GG",
    "name": "Guernsey",
    "display_name": "Guernsey (GG) [+44]",
  },
  {
    "phone_code": "224",
    "country_code": "GN",
    "name": "Guinea Conakry",
    "display_name": "Guinea Conakry (GN) [+224]",
  },
  {
    "phone_code": "245",
    "country_code": "GW",
    "name": "Guinea-Bissau",
    "display_name": "Guinea-Bissau (GW) [+245]",
  },
  {
    "phone_code": "592",
    "country_code": "GY",
    "name": "Guyana",
    "display_name": "Guyana (GY) [+592]",
  },
  {
    "phone_code": "509",
    "country_code": "HT",
    "name": "Haiti",
    "display_name": "Haiti (HT) [+509]",
  },
  {
    "phone_code": "672",
    "country_code": "HM",
    "name": "Heard Island and McDonald Islands",
    "display_name": "Heard Island and McDonald Islands (HM) [+672]",
  },
  {
    "phone_code": "504",
    "country_code": "HN",
    "name": "Honduras",
    "display_name": "Honduras (HN) [+504]",
  },
  {
    "phone_code": "852",
    "country_code": "HK",
    "name": "Hong Kong",
    "display_name": "Hong Kong (HK) [+852]",
  },
  {
    "phone_code": "36",
    "country_code": "HU",
    "name": "Hungary",
    "display_name": "Hungary (HU) [+36]",
  },
  {
    "phone_code": "354",
    "country_code": "IS",
    "name": "Iceland",
    "display_name": "Iceland (IS) [+354]",
  },
  {
    "phone_code": "91",
    "country_code": "IN",
    "name": "India",
    "display_name": "India (IN) [+91]",
  },
  {
    "phone_code": "62",
    "country_code": "ID",
    "name": "Indonesia",
    "display_name": "Indonesia (ID) [+62]",
  },
  {
    "phone_code": "98",
    "country_code": "IR",
    "name": "Iran",
    "display_name": "Iran (IR) [+98]",
  },
  {
    "phone_code": "964",
    "country_code": "IQ",
    "name": "Iraq",
    "display_name": "Iraq (IQ) [+964]",
  },
  {
    "phone_code": "353",
    "country_code": "IE",
    "name": "Ireland",
    "display_name": "Ireland (IE) [+353]",
  },
  {
    "phone_code": "44",
    "country_code": "IM",
    "name": "Isle of Man",
    "display_name": "Isle of Man (IM) [+44]",
  },
  {
    "phone_code": "972",
    "country_code": "IL",
    "name": "Israel",
    "display_name": "Israel (IL) [+972]",
  },
  {
    "phone_code": "39",
    "country_code": "IT",
    "name": "Italy",
    "display_name": "Italy (IT) [+39]",
  },
  {
    "phone_code": "1",
    "country_code": "JM",
    "name": "Jamaica",
    "display_name": "Jamaica (JM) [+1]",
  },
  {
    "phone_code": "81",
    "country_code": "JP",
    "name": "Japan",
    "display_name": "Japan (JP) [+81]",
  },
  {
    "phone_code": "44",
    "country_code": "JE",
    "name": "Jersey",
    "display_name": "Jersey (JE) [+44]",
  },
  {
    "phone_code": "962",
    "country_code": "JO",
    "name": "Jordan",
    "display_name": "Jordan (JO) [+962]",
  },
  {
    "phone_code": "7",
    "country_code": "KZ",
    "name": "Kazakhstan",
    "display_name": "Kazakhstan (KZ) [+7]",
  },
  {
    "phone_code": "254",
    "country_code": "KE",
    "name": "Kenya",
    "display_name": "Kenya (KE) [+254]",
  },
  {
    "phone_code": "686",
    "country_code": "KI",
    "name": "Kiribati",
    "display_name": "Kiribati (KI) [+686]",
  },
  {
    "phone_code": "383",
    "country_code": "XK",
    "name": "Kosovo",
    "display_name": "Kosovo (XK) [+383]",
  },
  {
    "phone_code": "381",
    "country_code": "XK",
    "name": "Kosovo",
    "display_name": "Kosovo (XK) [+381]",
  },
  {
    "phone_code": "386",
    "country_code": "XK",
    "name": "Kosovo",
    "display_name": "Kosovo (XK) [+386]",
  },
  {
    "phone_code": "965",
    "country_code": "KW",
    "name": "Kuwait",
    "display_name": "Kuwait (KW) [+965]",
  },
  {
    "phone_code": "996",
    "country_code": "KG",
    "name": "Kyrgyzstan",
    "display_name": "Kyrgyzstan (KG) [+996]",
  },
  {
    "phone_code": "856",
    "country_code": "LA",
    "name": "Laos",
    "display_name": "Laos (LA) [+856]",
  },
  {
    "phone_code": "371",
    "country_code": "LV",
    "name": "Latvia",
    "display_name": "Latvia (LV) [+371]",
  },
  {
    "phone_code": "961",
    "country_code": "LB",
    "name": "Lebanon",
    "display_name": "Lebanon (LB) [+961]",
  },
  {
    "phone_code": "266",
    "country_code": "LS",
    "name": "Lesotho",
    "display_name": "Lesotho (LS) [+266]",
  },
  {
    "phone_code": "231",
    "country_code": "LR",
    "name": "Liberia",
    "display_name": "Liberia (LR) [+231]",
  },
  {
    "phone_code": "218",
    "country_code": "LY",
    "name": "Libya",
    "display_name": "Libya (LY) [+218]",
  },
  {
    "phone_code": "423",
    "country_code": "LI",
    "name": "Liechtenstein",
    "display_name": "Liechtenstein (LI) [+423]",
  },
  {
    "phone_code": "370",
    "country_code": "LT",
    "name": "Lithuania",
    "display_name": "Lithuania (LT) [+370]",
  },
  {
    "phone_code": "352",
    "country_code": "LU",
    "name": "Luxembourg",
    "display_name": "Luxembourg (LU) [+352]",
  },
  {
    "phone_code": "853",
    "country_code": "MO",
    "name": "Macau",
    "display_name": "Macau (MO) [+853]",
  },
  {
    "phone_code": "389",
    "country_code": "MK",
    "name": "Macedonia",
    "display_name": "Macedonia (MK) [+389]",
  },
  {
    "phone_code": "261",
    "country_code": "MG",
    "name": "Madagascar",
    "display_name": "Madagascar (MG) [+261]",
  },
  {
    "phone_code": "265",
    "country_code": "MW",
    "name": "Malawi",
    "display_name": "Malawi (MW) [+265]",
  },
  {
    "phone_code": "60",
    "country_code": "MY",
    "name": "Malaysia",
    "display_name": "Malaysia (MY) [+60]",
  },
  {
    "phone_code": "960",
    "country_code": "MV",
    "name": "Maldives",
    "display_name": "Maldives (MV) [+960]",
  },
  {
    "phone_code": "223",
    "country_code": "ML",
    "name": "Mali",
    "display_name": "Mali (ML) [+223]",
  },
  {
    "phone_code": "356",
    "country_code": "MT",
    "name": "Malta",
    "display_name": "Malta (MT) [+356]",
  },
  {
    "phone_code": "692",
    "country_code": "MH",
    "name": "Marshall Islands",
    "display_name": "Marshall Islands (MH) [+692]",
  },
  {
    "phone_code": "596",
    "country_code": "MQ",
    "name": "Martinique",
    "display_name": "Martinique (MQ) [+596]",
  },
  {
    "phone_code": "222",
    "country_code": "MR",
    "name": "Mauritania",
    "display_name": "Mauritania (MR) [+222]",
  },
  {
    "phone_code": "230",
    "country_code": "MU",
    "name": "Mauritius",
    "display_name": "Mauritius (MU) [+230]",
  },
  {
    "phone_code": "262",
    "country_code": "YT",
    "name": "Mayotte",
    "display_name": "Mayotte (YT) [+262]",
  },
  {
    "phone_code": "52",
    "country_code": "MX",
    "name": "Mexico",
    "display_name": "Mexico (MX) [+52]",
  },
  {
    "phone_code": "691",
    "country_code": "FM",
    "name": "Micronesia",
    "display_name": "Micronesia (FM) [+691]",
  },
  {
    "phone_code": "373",
    "country_code": "MD",
    "name": "Moldova",
    "display_name": "Moldova (MD) [+373]",
  },
  {
    "phone_code": "377",
    "country_code": "MC",
    "name": "Monaco",
    "display_name": "Monaco (MC) [+377]",
  },
  {
    "phone_code": "976",
    "country_code": "MN",
    "name": "Mongolia",
    "display_name": "Mongolia (MN) [+976]",
  },
  {
    "phone_code": "382",
    "country_code": "ME",
    "name": "Montenegro",
    "display_name": "Montenegro (ME) [+382]",
  },
  {
    "phone_code": "1",
    "country_code": "MS",
    "name": "Montserrat",
    "display_name": "Montserrat (MS) [+1]",
  },
  {
    "phone_code": "212",
    "country_code": "MA",
    "name": "Morocco",
    "display_name": "Morocco (MA) [+212]",
  },
  {
    "phone_code": "258",
    "country_code": "MZ",
    "name": "Mozambique",
    "display_name": "Mozambique (MZ) [+258]",
  },
  {
    "phone_code": "95",
    "country_code": "MM",
    "name": "Myanmar [Burma]",
    "display_name": "Myanmar [Burma] (MM) [+95]",
  },
  {
    "phone_code": "264",
    "country_code": "NA",
    "name": "Namibia",
    "display_name": "Namibia (NA) [+264]",
  },
  {
    "phone_code": "674",
    "country_code": "NR",
    "name": "Nauru",
    "display_name": "Nauru (NR) [+674]",
  },
  {
    "phone_code": "977",
    "country_code": "NP",
    "name": "Nepal",
    "display_name": "Nepal (NP) [+977]",
  },
  {
    "phone_code": "31",
    "country_code": "NL",
    "name": "Netherlands",
    "display_name": "Netherlands (NL) [+31]",
  },
  {
    "phone_code": "687",
    "country_code": "NC",
    "name": "New Caledonia",
    "display_name": "New Caledonia (NC) [+687]",
  },
  {
    "phone_code": "64",
    "country_code": "NZ",
    "name": "New Zealand",
    "display_name": "New Zealand (NZ) [+64]",
  },
  {
    "phone_code": "505",
    "country_code": "NI",
    "name": "Nicaragua",
    "display_name": "Nicaragua (NI) [+505]",
  },
  {
    "phone_code": "227",
    "country_code": "NE",
    "name": "Niger",
    "display_name": "Niger (NE) [+227]",
  },
  {
    "phone_code": "234",
    "country_code": "NG",
    "name": "Nigeria",
    "display_name": "Nigeria (NG) [+234]",
  },
  {
    "phone_code": "683",
    "country_code": "NU",
    "name": "Niue",
    "display_name": "Niue (NU) [+683]",
  },
  {
    "phone_code": "672",
    "country_code": "NF",
    "name": "Norfolk Island",
    "display_name": "Norfolk Island (NF) [+672]",
  },
  {
    "phone_code": "850",
    "country_code": "KP",
    "name": "North Korea",
    "display_name": "North Korea (KP) [+850]",
  },
  {
    "phone_code": "1",
    "country_code": "MP",
    "name": "Northern Mariana Islands",
    "display_name": "Northern Mariana Islands (MP) [+1]",
  },
  {
    "phone_code": "47",
    "country_code": "NO",
    "name": "Norway",
    "display_name": "Norway (NO) [+47]",
  },
  {
    "phone_code": "968",
    "country_code": "OM",
    "name": "Oman",
    "display_name": "Oman (OM) [+968]",
  },
  {
    "phone_code": "92",
    "country_code": "PK",
    "name": "Pakistan",
    "display_name": "Pakistan (PK) [+92]",
  },
  {
    "phone_code": "680",
    "country_code": "PW",
    "name": "Palau",
    "display_name": "Palau (PW) [+680]",
  },
  {
    "phone_code": "970",
    "country_code": "PS",
    "name": "Palestinian Territories",
    "display_name": "Palestinian Territories (PS) [+970]",
  },
  {
    "phone_code": "507",
    "country_code": "PA",
    "name": "Panama",
    "display_name": "Panama (PA) [+507]",
  },
  {
    "phone_code": "675",
    "country_code": "PG",
    "name": "Papua New Guinea",
    "display_name": "Papua New Guinea (PG) [+675]",
  },
  {
    "phone_code": "595",
    "country_code": "PY",
    "name": "Paraguay",
    "display_name": "Paraguay (PY) [+595]",
  },
  {
    "phone_code": "51",
    "country_code": "PE",
    "name": "Peru",
    "display_name": "Peru (PE) [+51]",
  },
  {
    "phone_code": "63",
    "country_code": "PH",
    "name": "Philippines",
    "display_name": "Philippines (PH) [+63]",
  },
  {
    "phone_code": "48",
    "country_code": "PL",
    "name": "Poland",
    "display_name": "Poland (PL) [+48]",
  },
  {
    "phone_code": "351",
    "country_code": "PT",
    "name": "Portugal",
    "display_name": "Portugal (PT) [+351]",
  },
  {
    "phone_code": "1",
    "country_code": "PR",
    "name": "Puerto Rico",
    "display_name": "Puerto Rico (PR) [+1]",
  },
  {
    "phone_code": "974",
    "country_code": "QA",
    "name": "Qatar",
    "display_name": "Qatar (QA) [+974]",
  },
  {
    "phone_code": "262",
    "country_code": "RE",
    "name": "Réunion",
    "display_name": "Réunion (RE) [+262]",
  },
  {
    "phone_code": "40",
    "country_code": "RO",
    "name": "Romania",
    "display_name": "Romania (RO) [+40]",
  },
  {
    "phone_code": "7",
    "country_code": "RU",
    "name": "Russia",
    "display_name": "Russia (RU) [+7]",
  },
  {
    "phone_code": "250",
    "country_code": "RW",
    "name": "Rwanda",
    "display_name": "Rwanda (RW) [+250]",
  },
  {
    "phone_code": "590",
    "country_code": "BL",
    "name": "Saint Barthélemy",
    "display_name": "Saint Barthélemy (BL) [+590]",
  },
  {
    "phone_code": "290",
    "country_code": "SH",
    "name": "Saint Helena",
    "display_name": "Saint Helena (SH) [+290]",
  },
  {
    "phone_code": "1",
    "country_code": "KN",
    "name": "St. Kitts",
    "display_name": "St. Kitts (KN) [+1]",
  },
  {
    "phone_code": "1",
    "country_code": "LC",
    "name": "St. Lucia",
    "display_name": "St. Lucia (LC) [+1]",
  },
  {
    "phone_code": "590",
    "country_code": "MF",
    "name": "Saint Martin",
    "display_name": "Saint Martin (MF) [+590]",
  },
  {
    "phone_code": "508",
    "country_code": "PM",
    "name": "Saint Pierre and Miquelon",
    "display_name": "Saint Pierre and Miquelon (PM) [+508]",
  },
  {
    "phone_code": "1",
    "country_code": "VC",
    "name": "St. Vincent",
    "display_name": "St. Vincent (VC) [+1]",
  },
  {
    "phone_code": "685",
    "country_code": "WS",
    "name": "Samoa",
    "display_name": "Samoa (WS) [+685]",
  },
  {
    "phone_code": "378",
    "country_code": "SM",
    "name": "San Marino",
    "display_name": "San Marino (SM) [+378]",
  },
  {
    "phone_code": "239",
    "country_code": "ST",
    "name": "São Tomé and Príncipe",
    "display_name": "São Tomé and Príncipe (ST) [+239]",
  },
  {
    "phone_code": "966",
    "country_code": "SA",
    "name": "Saudi Arabia",
    "display_name": "Saudi Arabia (SA) [+966]",
  },
  {
    "phone_code": "221",
    "country_code": "SN",
    "name": "Senegal",
    "display_name": "Senegal (SN) [+221]",
  },
  {
    "phone_code": "381",
    "country_code": "RS",
    "name": "Serbia",
    "display_name": "Serbia (RS) [+381]",
  },
  {
    "phone_code": "248",
    "country_code": "SC",
    "name": "Seychelles",
    "display_name": "Seychelles (SC) [+248]",
  },
  {
    "phone_code": "232",
    "country_code": "SL",
    "name": "Sierra Leone",
    "display_name": "Sierra Leone (SL) [+232]",
  },
  {
    "phone_code": "65",
    "country_code": "SG",
    "name": "Singapore",
    "display_name": "Singapore (SG) [+65]",
  },
  {
    "phone_code": "1",
    "country_code": "SX",
    "name": "Sint Maarten",
    "display_name": "Sint Maarten (SX) [+1]",
  },
  {
    "phone_code": "421",
    "country_code": "SK",
    "name": "Slovakia",
    "display_name": "Slovakia (SK) [+421]",
  },
  {
    "phone_code": "386",
    "country_code": "SI",
    "name": "Slovenia",
    "display_name": "Slovenia (SI) [+386]",
  },
  {
    "phone_code": "677",
    "country_code": "SB",
    "name": "Solomon Islands",
    "display_name": "Solomon Islands (SB) [+677]",
  },
  {
    "phone_code": "252",
    "country_code": "SO",
    "name": "Somalia",
    "display_name": "Somalia (SO) [+252]",
  },
  {
    "phone_code": "27",
    "country_code": "ZA",
    "name": "South Africa",
    "display_name": "South Africa (ZA) [+27]",
  },
  {
    "phone_code": "500",
    "country_code": "GS",
    "name": "South Georgia and the South Sandwich Islands",
    "display_name": "South Georgia and the South Sandwich Islands (GS) [+500]",
    "e164_key": "500-GS-0"
  },
  {
    "phone_code": "82",
    "country_code": "KR",
    "name": "South Korea",
    "display_name": "South Korea (KR) [+82]",
  },
  {
    "phone_code": "211",
    "country_code": "SS",
    "name": "South Sudan",
    "display_name": "South Sudan (SS) [+211]",
  },
  {
    "phone_code": "34",
    "country_code": "ES",
    "name": "Spain",
    "display_name": "Spain (ES) [+34]",
  },
  {
    "phone_code": "94",
    "country_code": "LK",
    "name": "Sri Lanka",
    "display_name": "Sri Lanka (LK) [+94]",
  },
  {
    "phone_code": "249",
    "country_code": "SD",
    "name": "Sudan",
    "display_name": "Sudan (SD) [+249]",
  },
  {
    "phone_code": "597",
    "country_code": "SR",
    "name": "Suriname",
    "display_name": "Suriname (SR) [+597]",
  },
  {
    "phone_code": "47",
    "country_code": "SJ",
    "name": "Svalbard and Jan Mayen",
    "display_name": "Svalbard and Jan Mayen (SJ) [+47]",
  },
  {
    "phone_code": "46",
    "country_code": "SE",
    "name": "Sweden",
    "display_name": "Sweden (SE) [+46]",
  },
  {
    "phone_code": "41",
    "country_code": "CH",
    "name": "Switzerland",
    "display_name": "Switzerland (CH) [+41]",
  },
  {
    "phone_code": "963",
    "country_code": "SY",
    "name": "Syria",
    "display_name": "Syria (SY) [+963]",
  },
  {
    "phone_code": "886",
    "country_code": "TW",
    "name": "Taiwan",
    "display_name": "Taiwan (TW) [+886]",
  },
  {
    "phone_code": "992",
    "country_code": "TJ",
    "name": "Tajikistan",
    "display_name": "Tajikistan (TJ) [+992]",
  },
  {
    "phone_code": "255",
    "country_code": "TZ",
    "name": "Tanzania",
    "display_name": "Tanzania (TZ) [+255]",
  },
  {
    "phone_code": "66",
    "country_code": "TH",
    "name": "Thailand",
    "display_name": "Thailand (TH) [+66]",
  },
  {
    "phone_code": "228",
    "country_code": "TG",
    "name": "Togo",
    "display_name": "Togo (TG) [+228]",
  },
  {
    "phone_code": "690",
    "country_code": "TK",
    "name": "Tokelau",
    "display_name": "Tokelau (TK) [+690]",
  },
  {
    "phone_code": "676",
    "country_code": "TO",
    "name": "Tonga",
    "display_name": "Tonga (TO) [+676]",
  },
  {
    "phone_code": "1",
    "country_code": "TT",
    "name": "Trinidad/Tobago",
    "display_name": "Trinidad/Tobago (TT) [+1]",
  },
  {
    "phone_code": "216",
    "country_code": "TN",
    "name": "Tunisia",
    "display_name": "Tunisia (TN) [+216]",
  },
  {
    "phone_code": "90",
    "country_code": "TR",
    "name": "Turkey",
    "display_name": "Turkey (TR) [+90]",
  },
  {
    "phone_code": "993",
    "country_code": "TM",
    "name": "Turkmenistan",
    "display_name": "Turkmenistan (TM) [+993]",
  },
  {
    "phone_code": "1",
    "country_code": "TC",
    "name": "Turks and Caicos Islands",
    "display_name": "Turks and Caicos Islands (TC) [+1]",
  },
  {
    "phone_code": "688",
    "country_code": "TV",
    "name": "Tuvalu",
    "display_name": "Tuvalu (TV) [+688]",
  },
  {
    "phone_code": "1",
    "country_code": "VI",
    "name": "U.S. Virgin Islands",
    "display_name": "U.S. Virgin Islands (VI) [+1]",
  },
  {
    "phone_code": "256",
    "country_code": "UG",
    "name": "Uganda",
    "display_name": "Uganda (UG) [+256]",
  },
  {
    "phone_code": "380",
    "country_code": "UA",
    "name": "Ukraine",
    "display_name": "Ukraine (UA) [+380]",
  },
  {
    "phone_code": "971",
    "country_code": "AE",
    "name": "United Arab Emirates",
    "display_name": "United Arab Emirates (AE) [+971]",
  },
  {
    "phone_code": "44",
    "country_code": "GB",
    "name": "United Kingdom",
    "display_name": "United Kingdom (GB) [+44]",
  },
  {
    "phone_code": "1",
    "country_code": "US",
    "name": "United States",
    "display_name": "United States (US) [+1]",
  },
  {
    "phone_code": "598",
    "country_code": "UY",
    "name": "Uruguay",
    "display_name": "Uruguay (UY) [+598]",
  },
  {
    "phone_code": "998",
    "country_code": "UZ",
    "name": "Uzbekistan",
    "display_name": "Uzbekistan (UZ) [+998]",
  },
  {
    "phone_code": "678",
    "country_code": "VU",
    "name": "Vanuatu",
    "display_name": "Vanuatu (VU) [+678]",
  },
  {
    "phone_code": "379",
    "country_code": "VA",
    "name": "Vatican City",
    "display_name": "Vatican City (VA) [+379]",
  },
  {
    "phone_code": "58",
    "country_code": "VE",
    "name": "Venezuela",
    "display_name": "Venezuela (VE) [+58]",
  },
  {
    "phone_code": "84",
    "country_code": "VN",
    "name": "Vietnam",
    "display_name": "Vietnam (VN) [+84]",
  },
  {
    "phone_code": "681",
    "country_code": "WF",
    "name": "Wallis and Futuna",
    "display_name": "Wallis and Futuna (WF) [+681]",
  },
  {
    "phone_code": "212",
    "country_code": "EH",
    "name": "Western Sahara",
    "display_name": "Western Sahara (EH) [+212]",
  },
  {
    "phone_code": "967",
    "country_code": "YE",
    "name": "Yemen",
    "display_name": "Yemen (YE) [+967]",
  },
  {
    "phone_code": "260",
    "country_code": "ZM",
    "name": "Zambia",
    "display_name": "Zambia (ZM) [+260]",
  },
  {
    "phone_code": "263",
    "country_code": "ZW",
    "name": "Zimbabwe",
    "display_name": "Zimbabwe (ZW) [+263]",
  }
];
